let currencyFullNames = [ "BGN" : "Bulgarian Lev",
                          "BRL" : "Brazilian Real",
                          "CHF" : "Switzerland Franc",
                          "CZK" : "Czech Republic Karuna",
                          "DKK" : "Danish Krona",
                          "HRK" : "Croatian Kuna",
                          "HUF" : "Hungarian Forint",
                          "IDR" : "Indonesian Rupiah",
                          "ILS" : "Israeli Shekel",
                          "INR" : "Indian Rupee",
                          "KRW" : "South Korean Won",
                          "MXN" : "Mexican Peso",
                          "MYR" : "Malaysian Ringgit",
                          "NOK" : "Norwegian Krone",
                          "PHP" : "Philippine Peso",
                          "PLN" : "Polish Zloty",
                          "RON" : "Romanian New Leu",
                          "RUB" : "Russian Ruble",
                          "SEK" : "Swedish Krona",
                          "SGD" : "Singapore Dollar", 
                          "THB" : "Thai Baht", 
                          "TRY" : "Turkish Lira", 
                          "ZAR" : "South African Rand", 
                          "CAD" : "Canadian Dollar",
                          "AUD" : "Australian Dollar", 
                          "EUR" : "European Euro", 
                          "NZD" : "New Zealand Dollar", 
                          "JPY" : "Japanese Yen",
                          "CNY" : "Chinese Yuan",
                          "HKD" : "Hong Kong Dollar", 
                          "GBP" : "British Pound",
                          "USD" : "United States Dollar" ]
